# Ameera config.toml

[main]
token = ""
# optional
MONGO_URL = ""
# get jeyy api key at https://api.jeyy.xyz/
JEYY_API = "" 
[PG_CONF]
PG_HOST = ""
PG_PORT = 5432
PG_USER = ""
# leave password if empty
PG_PASS = ""
PG_DB = ""
